/** Safety and Compliance page and Cookie Policy, one document per language. The safety page carries over the substance of the
 *  previous site's /safety-compliance page; the cookie policy matches what the site actually sets (see components/Consent.tsx). */
import type { LegalDoc } from "./legal";

export const SAFETY: Record<string, LegalDoc> = {
  en: {
    title: "Safety and Compliance",
    updated: "Last updated: 17 September 2026",
    description: "Optavius is built for healthcare accountability: full audit trails, escalation protocols, HIPAA, SOC 1 and GDPR compliant data handling, and clinical governance by design.",
    intro: "Optavius is workflow automation for specialty care practices. It answers calls, books and moves appointments, gives order status and routes patients. It does not diagnose and never overrides clinical judgment. Every pathway, every decision and every escalation is documented and auditable. This page describes how safety, data protection and clinical governance are built in.",
    sections: [
      { id: "scope", title: "1. Scope statement", paragraphs: ["Optavius handles administrative patient interactions: navigation, scheduling, order status, reminders and follow-up. It provides no medical advice. When a caller describes symptoms, the agent applies the practice's own protocol to decide how urgently a person needs to be seen and by whom, and it hands over to staff whenever the protocol or the caller asks for it."] },
      { id: "escalation", title: "2. Escalation principles", paragraphs: ["Red-flag symptoms trigger immediate escalation to clinical staff, with the transcript and a short summary. When the agent is uncertain, it routes to a human rather than guessing. Safety comes before automation, always."], items: ["Red-flag symptom lists are defined and approved by the practice's clinical lead.", "Urgent cases are transferred live during opening hours and escalated by phone or message outside them.", "Callers can reach a person at any point by asking for one."] },
      { id: "audit", title: "3. Complete audit trail", paragraphs: ["Every decision the agent takes is logged. Each call has a full transcript with structured data: reason for calling, actions taken, outcome and any escalation. Pathways are versioned, so the practice can see which rules applied to any call at any time."] },
      { id: "oversight", title: "4. Human oversight", paragraphs: ["Flagged cases land in a review queue in the console. Pathways go live only after the practice's clinical governance has approved them, and edge cases are handled by people, not by the agent."] },
      { id: "data", title: "5. Data handling and security", paragraphs: ["Healthcare-grade security for all patient data, with encryption, access controls and compliance built in."], items: ["Encryption in transit and at rest.", "Role-based access with audit logging.", "Configurable retention policies per practice.", "HIPAA compliant data handling with a signed Business Associate Agreement for US practices.", "GDPR compliant processing for practices in the EU, with a data processing agreement.", "Controls aligned with SOC 1 and ISO 27001, and readiness for the EU AI Act."] },
      { id: "transparency", title: "6. Transparency by default", paragraphs: ["Patients always know what they are talking to."], items: ["Callers are told they are speaking with an AI assistant.", "Hand-offs to human staff are announced clearly.", "Full transcripts are available to the practice, and to patients on request through the practice."] },
      { id: "governance", title: "7. Clinical governance", paragraphs: ["We work with the practice's clinical leadership to design pathways that meet its governance standards."], items: ["Pathways are co-designed with the practice's clinical leadership.", "All routing rules are reviewed and approved before deployment.", "Pathways are audited and updated regularly.", "Escalation chains are documented and known to the team."] },
      { id: "contact", title: "8. Questions about compliance", paragraphs: ["Our team is happy to discuss your requirements and to share our security and compliance one-pager for your procurement team. Write to legal@optavius.com or book a demo."] },
    ],
  },
  nl: {
    title: "Veiligheid en compliance",
    updated: "Laatst bijgewerkt: 17 september 2026",
    description: "Optavius is gebouwd voor verantwoording in de zorg: volledige audittrails, escalatieprotocollen, HIPAA-, SOC 1- en AVG-conforme gegevensverwerking en klinische governance by design.",
    intro: "Optavius is workflowautomatisering voor specialistische praktijken. Het beantwoordt gesprekken, plant en verzet afspraken, geeft orderstatus en verwijst patiënten door. Het stelt geen diagnoses en gaat nooit boven het klinisch oordeel. Elk pad, elke beslissing en elke escalatie is gedocumenteerd en controleerbaar. Deze pagina beschrijft hoe veiligheid, gegevensbescherming en klinische governance zijn ingebouwd.",
    sections: [
      { id: "scope", title: "1. Reikwijdte", paragraphs: ["Optavius handelt administratieve patiëntcontacten af: routeren, plannen, orderstatus, herinneringen en opvolging. Het geeft geen medisch advies. Beschrijft een beller klachten, dan past de agent het eigen protocol van de praktijk toe om te bepalen hoe snel iemand gezien moet worden en door wie, en draagt over aan een medewerker zodra het protocol of de beller daarom vraagt."] },
      { id: "escalation", title: "2. Escalatieprincipes", paragraphs: ["Alarmsymptomen leiden tot directe escalatie naar klinisch personeel, met transcript en korte samenvatting. Bij twijfel schakelt de agent een mens in in plaats van te gokken. Veiligheid gaat altijd vóór automatisering."], items: ["Lijsten met alarmsymptomen worden vastgesteld en goedgekeurd door de klinisch verantwoordelijke van de praktijk.", "Urgente gevallen worden tijdens openingstijden live doorverbonden en daarbuiten telefonisch of per bericht geëscaleerd.", "Bellers kunnen op elk moment een medewerker bereiken door daarom te vragen."] },
      { id: "audit", title: "3. Volledige audittrail", paragraphs: ["Elke beslissing van de agent wordt gelogd. Elk gesprek heeft een volledig transcript met gestructureerde gegevens: reden van bellen, ondernomen acties, uitkomst en eventuele escalatie. Paden zijn geversioneerd, zodat de praktijk altijd kan zien welke regels bij welk gesprek golden."] },
      { id: "oversight", title: "4. Menselijk toezicht", paragraphs: ["Gemarkeerde gevallen komen in een beoordelingswachtrij in de console. Paden gaan pas live na goedkeuring door de klinische governance van de praktijk, en uitzonderingen worden door mensen afgehandeld, niet door de agent."] },
      { id: "data", title: "5. Gegevensverwerking en beveiliging", paragraphs: ["Beveiliging op zorgniveau voor alle patiëntgegevens, met versleuteling, toegangsbeheer en compliance ingebouwd."], items: ["Versleuteling onderweg en in rust.", "Rolgebaseerde toegang met auditlogging.", "Instelbaar bewaarbeleid per praktijk.", "HIPAA-conforme verwerking met een getekende Business Associate Agreement voor Amerikaanse praktijken.", "AVG-conforme verwerking voor praktijken in de EU, met een verwerkersovereenkomst.", "Maatregelen in lijn met SOC 1 en ISO 27001, en voorbereid op de EU AI Act."] },
      { id: "transparency", title: "6. Transparantie als standaard", paragraphs: ["Patiënten weten altijd met wie of wat ze spreken."], items: ["Bellers horen dat ze met een AI-assistent spreken.", "Overdrachten naar medewerkers worden duidelijk aangekondigd.", "Volledige transcripten zijn beschikbaar voor de praktijk, en op verzoek via de praktijk voor patiënten."] },
      { id: "governance", title: "7. Klinische governance", paragraphs: ["We werken samen met de klinische leiding van de praktijk aan paden die voldoen aan haar governancenormen."], items: ["Paden worden samen met de klinische leiding van de praktijk ontworpen.", "Alle routeringsregels worden vóór livegang beoordeeld en goedgekeurd.", "Paden worden regelmatig geaudit en bijgewerkt.", "Escalatieketens zijn gedocumenteerd en bekend bij het team."] },
      { id: "contact", title: "8. Vragen over compliance", paragraphs: ["Ons team bespreekt graag uw eisen en deelt onze onepager over beveiliging en compliance voor uw inkoopteam. Mail naar legal@optavius.com of vraag een demo aan."] },
    ],
  },
  de: {
    title: "Sicherheit und Compliance",
    updated: "Zuletzt aktualisiert: 17. September 2026",
    description: "Optavius ist für Verantwortlichkeit im Gesundheitswesen gebaut: vollständige Audit-Trails, Eskalationsprotokolle, HIPAA-, SOC-1- und DSGVO-konforme Datenverarbeitung und klinische Governance by Design.",
    intro: "Optavius ist Workflow-Automatisierung für Facharztpraxen. Es beantwortet Anrufe, bucht und verschiebt Termine, gibt Auskunft zum Bestellstatus und leitet Patienten weiter. Es stellt keine Diagnosen und stellt sich nie über das klinische Urteil. Jeder Pfad, jede Entscheidung und jede Eskalation ist dokumentiert und prüfbar. Diese Seite beschreibt, wie Sicherheit, Datenschutz und klinische Governance eingebaut sind.",
    sections: [
      { id: "scope", title: "1. Geltungsbereich", paragraphs: ["Optavius übernimmt administrative Patientenkontakte: Weiterleitung, Terminplanung, Bestellstatus, Erinnerungen und Nachsorge. Es gibt keine medizinischen Ratschläge. Schildert ein Anrufer Beschwerden, wendet der Agent das eigene Protokoll der Praxis an, um zu bestimmen, wie dringend und von wem jemand gesehen werden muss, und übergibt an Mitarbeitende, sobald das Protokoll oder der Anrufer es verlangt."] },
      { id: "escalation", title: "2. Eskalationsprinzipien", paragraphs: ["Warnsymptome führen zur sofortigen Eskalation an klinisches Personal, mit Transkript und kurzer Zusammenfassung. Ist der Agent unsicher, leitet er an einen Menschen weiter, statt zu raten. Sicherheit geht immer vor Automatisierung."], items: ["Listen mit Warnsymptomen werden von der klinischen Leitung der Praxis festgelegt und freigegeben.", "Dringende Fälle werden zu Öffnungszeiten live durchgestellt und außerhalb per Telefon oder Nachricht eskaliert.", "Anrufer erreichen jederzeit eine Person, wenn sie danach fragen."] },
      { id: "audit", title: "3. Vollständiger Audit-Trail", paragraphs: ["Jede Entscheidung des Agenten wird protokolliert. Jeder Anruf hat ein vollständiges Transkript mit strukturierten Daten: Anrufgrund, ergriffene Maßnahmen, Ergebnis und etwaige Eskalation. Pfade sind versioniert, sodass die Praxis jederzeit sehen kann, welche Regeln bei welchem Anruf galten."] },
      { id: "oversight", title: "4. Menschliche Aufsicht", paragraphs: ["Markierte Fälle landen in einer Prüfwarteschlange in der Konsole. Pfade gehen erst live, wenn die klinische Governance der Praxis sie freigegeben hat, und Sonderfälle bearbeiten Menschen, nicht der Agent."] },
      { id: "data", title: "5. Datenverarbeitung und Sicherheit", paragraphs: ["Sicherheit auf Gesundheitsniveau für alle Patientendaten, mit Verschlüsselung, Zugriffskontrollen und eingebauter Compliance."], items: ["Verschlüsselung bei Übertragung und Speicherung.", "Rollenbasierter Zugriff mit Audit-Protokollierung.", "Konfigurierbare Aufbewahrungsregeln je Praxis.", "HIPAA-konforme Verarbeitung mit unterzeichnetem Business Associate Agreement für US-Praxen.", "DSGVO-konforme Verarbeitung für Praxen in der EU, mit Auftragsverarbeitungsvertrag.", "Kontrollen im Einklang mit SOC 1 und ISO 27001 sowie Vorbereitung auf den EU AI Act."] },
      { id: "transparency", title: "6. Transparenz als Standard", paragraphs: ["Patienten wissen immer, mit wem oder was sie sprechen."], items: ["Anrufer erfahren, dass sie mit einem KI-Assistenten sprechen.", "Übergaben an Mitarbeitende werden klar angekündigt.", "Vollständige Transkripte stehen der Praxis zur Verfügung, und Patienten auf Anfrage über die Praxis."] },
      { id: "governance", title: "7. Klinische Governance", paragraphs: ["Wir arbeiten mit der klinischen Leitung der Praxis an Pfaden, die ihren Governance-Standards entsprechen."], items: ["Pfade werden gemeinsam mit der klinischen Leitung der Praxis entworfen.", "Alle Weiterleitungsregeln werden vor dem Livegang geprüft und freigegeben.", "Pfade werden regelmäßig auditiert und aktualisiert.", "Eskalationsketten sind dokumentiert und dem Team bekannt."] },
      { id: "contact", title: "8. Fragen zur Compliance", paragraphs: ["Unser Team bespricht gern Ihre Anforderungen und teilt unseren Sicherheits- und Compliance-Einseiter für Ihren Einkauf. Schreiben Sie an legal@optavius.com oder buchen Sie eine Demo."] },
    ],
  },
};

export const COOKIES: Record<string, LegalDoc> = {
  en: {
    title: "Cookie Policy",
    updated: "Last updated: 17 September 2026",
    description: "How optavius.com uses cookies and similar technologies, what is set only with your consent, and how to change your choice.",
    intro: "This policy explains which cookies and similar technologies optavius.com uses, why, and how you can control them. It complements our Privacy Policy.",
    sections: [
      { id: "what", title: "1. What cookies are", paragraphs: ["Cookies are small text files that a website stores on your device. Similar technologies, such as browser storage, work in the same way. They can keep a setting between visits, recognise a returning browser or help us understand how the site is used."] },
      { id: "use", title: "2. What we set and why", paragraphs: ["We keep the site as light as possible. Nothing is set for analytics until you have said yes in the banner."], items: ["Your consent choice: one entry in your browser's local storage that remembers whether you accepted or declined analytics, so we do not ask again on every visit. It contains no personal data.", "Analytics (only after consent): PostHog, hosted in the EU, records page views and clicks so we can see which pages help visitors and which do not. It sets cookies with the prefix ph_ that identify a browser, not a person.", "Booking: when you open the demo calendar, Cal.com may set its own functional cookies for the booking flow. These are governed by Cal.com's policy."] },
      { id: "no", title: "3. What we do not do", paragraphs: ["We set no advertising or marketing cookies, and we do not sell or share visitor data with advertisers."] },
      { id: "manage", title: "4. Managing your choice", paragraphs: ["You can accept or decline analytics in the banner on your first visit. To change your choice later, clear the site's data in your browser and the banner will appear again, or block cookies for optavius.com in your browser settings. Declining analytics does not limit the site in any way."] },
      { id: "contact", title: "5. Contact", paragraphs: ["Questions about this policy: privacy@optavius.com."] },
    ],
  },
  nl: {
    title: "Cookiebeleid",
    updated: "Laatst bijgewerkt: 17 september 2026",
    description: "Hoe optavius.com cookies en vergelijkbare technieken gebruikt, wat alleen met uw toestemming wordt geplaatst en hoe u uw keuze aanpast.",
    intro: "Dit beleid legt uit welke cookies en vergelijkbare technieken optavius.com gebruikt, waarom, en hoe u ze beheert. Het is een aanvulling op ons privacybeleid.",
    sections: [
      { id: "what", title: "1. Wat cookies zijn", paragraphs: ["Cookies zijn kleine tekstbestanden die een website op uw apparaat opslaat. Vergelijkbare technieken, zoals browseropslag, werken op dezelfde manier. Ze kunnen een instelling bewaren tussen bezoeken, een terugkerende browser herkennen of ons helpen te begrijpen hoe de site wordt gebruikt."] },
      { id: "use", title: "2. Wat we plaatsen en waarom", paragraphs: ["We houden de site zo licht mogelijk. Voor analyse wordt niets geplaatst totdat u in de banner ja hebt gezegd."], items: ["Uw toestemmingskeuze: één vermelding in de lokale opslag van uw browser die onthoudt of u analyse hebt geaccepteerd of geweigerd, zodat we het niet bij elk bezoek opnieuw vragen. Deze bevat geen persoonsgegevens.", "Analyse (alleen na toestemming): PostHog, gehost in de EU, registreert paginaweergaven en klikken zodat we zien welke pagina's bezoekers helpen en welke niet. Het plaatst cookies met het voorvoegsel ph_ die een browser identificeren, geen persoon.", "Afspraken: als u de demokalender opent, kan Cal.com eigen functionele cookies plaatsen voor het boekingsproces. Daarvoor geldt het beleid van Cal.com."] },
      { id: "no", title: "3. Wat we niet doen", paragraphs: ["We plaatsen geen advertentie- of marketingcookies en we verkopen of delen geen bezoekersgegevens met adverteerders."] },
      { id: "manage", title: "4. Uw keuze beheren", paragraphs: ["Bij uw eerste bezoek kunt u analyse in de banner accepteren of weigeren. Wilt u uw keuze later wijzigen, wis dan de sitegegevens in uw browser; de banner verschijnt dan opnieuw. U kunt cookies voor optavius.com ook blokkeren in uw browserinstellingen. Weigeren beperkt de site op geen enkele manier."] },
      { id: "contact", title: "5. Contact", paragraphs: ["Vragen over dit beleid: privacy@optavius.com."] },
    ],
  },
  de: {
    title: "Cookie-Richtlinie",
    updated: "Zuletzt aktualisiert: 17. September 2026",
    description: "Wie optavius.com Cookies und ähnliche Technologien nutzt, was nur mit Ihrer Einwilligung gesetzt wird und wie Sie Ihre Wahl ändern.",
    intro: "Diese Richtlinie erklärt, welche Cookies und ähnlichen Technologien optavius.com nutzt, warum, und wie Sie sie steuern können. Sie ergänzt unsere Datenschutzerklärung.",
    sections: [
      { id: "what", title: "1. Was Cookies sind", paragraphs: ["Cookies sind kleine Textdateien, die eine Website auf Ihrem Gerät speichert. Ähnliche Technologien wie der Browserspeicher funktionieren genauso. Sie können eine Einstellung zwischen Besuchen bewahren, einen wiederkehrenden Browser erkennen oder uns helfen zu verstehen, wie die Seite genutzt wird."] },
      { id: "use", title: "2. Was wir setzen und warum", paragraphs: ["Wir halten die Seite so leicht wie möglich. Für Analysen wird nichts gesetzt, bevor Sie im Banner zugestimmt haben."], items: ["Ihre Einwilligungswahl: ein Eintrag im lokalen Speicher Ihres Browsers, der festhält, ob Sie Analysen akzeptiert oder abgelehnt haben, damit wir nicht bei jedem Besuch erneut fragen. Er enthält keine personenbezogenen Daten.", "Analysen (nur nach Einwilligung): PostHog, in der EU gehostet, erfasst Seitenaufrufe und Klicks, damit wir sehen, welche Seiten Besuchern helfen und welche nicht. Es setzt Cookies mit dem Präfix ph_, die einen Browser identifizieren, keine Person.", "Terminbuchung: Wenn Sie den Demo-Kalender öffnen, kann Cal.com eigene funktionale Cookies für den Buchungsablauf setzen. Dafür gilt die Richtlinie von Cal.com."] },
      { id: "no", title: "3. Was wir nicht tun", paragraphs: ["Wir setzen keine Werbe- oder Marketing-Cookies und verkaufen oder teilen keine Besucherdaten mit Werbetreibenden."] },
      { id: "manage", title: "4. Ihre Wahl verwalten", paragraphs: ["Beim ersten Besuch können Sie Analysen im Banner akzeptieren oder ablehnen. Um Ihre Wahl später zu ändern, löschen Sie die Website-Daten in Ihrem Browser; der Banner erscheint dann erneut. Sie können Cookies für optavius.com auch in den Browsereinstellungen blockieren. Ablehnen schränkt die Seite in keiner Weise ein."] },
      { id: "contact", title: "5. Kontakt", paragraphs: ["Fragen zu dieser Richtlinie: privacy@optavius.com."] },
    ],
  },
};
